### ISSUE TITLE
Need to update to work with the latest patch.

### ISSUE THREAD

**Issue by Xyrmes** [cabarius/ToyBox#674] opened 2022-08-30 16:32 UTC
**Describe the bug**
UMM says this mod is non-functional with the latest DLC/patch. It was already janky over the last few months, such as not being able to remove items from inventory, for example. Now, it's even worse.

**To Reproduce**
1. Open the game
2. Wait to load to the main menu
3. UMM opens automatically, and marks this mod in red due to not being compatible with latest version

**Expected behavior**
UMM not saying this mod isn't functional. Ideally, having its full functionality restored, as well.

**Save Files**
To help us reproduce your issue, please attach a named *save file*
Please zip it or GitHub will not accept it.

<img width="1920" alt="Toybox Error" src="https://user-images.githubusercontent.com/31435121/187491097-b448f5f3-0c1f-4108-89e5-d54040370127.png">

**Comment by shadowdacer18** [comment] 2022-08-30 18:05
Would simply like to say i am also experinecing this so i'll get a notification when it's answered, love the work done on the mod in general

**Comment by PlowPlow666** [comment] 2022-08-30 19:50
Samething for me. I uninstall then install both mod and unity and nothing seems to work

**Comment by pmabraham** [comment] 2022-08-30 20:35
1.4.0Y was released today per https://store.steampowered.com/news/app/1184370/view/3225161106688762145

I appreciate the developer as this has made playing Wotr enjoyable compared to the base game without the mod.  It would be nice for this mod to be updated for 1.4.0y.  Thank you!

**Comment by Joesk** [comment] 2022-08-30 23:32
The UnityModManager installer app shows that the ver 1.4.17 is available, but I can't find it to DL.

**Comment by biggayenergy** [comment] 2022-08-31 02:12
> The UnityModManager installer app shows that the ver 1.4.17 is available, but I can't find it to DL.

That's just how the mod itself is coded at the moment. It's listed as 1.4.17 in the code of the 1.4.16 release so you're already at 1.4.17 technically. I think it's a minor error and easily fixed once they publish the new update. We'll probably see 1.4.18 at the next update.

**Comment by biggayenergy** [comment] 2022-08-31 02:19
My mistake - the 1.4.17 looks like a beta release.

**Comment by Xyrmes** [comment] 2022-08-31 02:58
Apparently a beta version is available on Discord: https://discord.com/channels/645948717400064030/815735034514112512/1004605890919399444

I installed it and it seems to get rid of the red flag from UMM, and it lets me add/remove items. So I guess it's working.

**Comment by shadowdacer18** [comment] 2022-08-31 07:05
the link you posted doesn't work for me, is there another link or way i'm doing it wrong?

**Comment by Autissima** [comment] 2022-08-31 08:07
The link posted is just a link to a discord message, not to the file itself, I would join the server and post the direct download link but I don't know if that's allowed and I'm not at home currently

**Comment by neekz0r** [comment] 2022-08-31 16:10
> Apparently a beta version is available on Discord: https://discord.com/channels/645948717400064030/815735034514112512/1004605890919399444
> 

Sadly, the discord invite no longer works. It would be nice if the code were pushed!

**Comment by smaitlx1** [comment] 2022-08-31 16:38
@Autissima, @Xyrmes, this repo is licensed under MIT, so sharing the direct download link that was in discord, or reuploading somewhere (google drive or something) and sharing that is within the license terms.

```
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, **including without limitation the rights
to** use, copy, modify, merge, **publish, distribute,** sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

**Comment by Xyrmes** [comment] 2022-08-31 19:17
> > Apparently a beta version is available on Discord: https://discord.com/channels/645948717400064030/815735034514112512/1004605890919399444
> 
> Sadly, the discord invite no longer works. It would be nice if the code were pushed!

I think that you have to join the Owlcat Discord server before you can access that link.

**Comment by neekz0r** [comment] 2022-08-31 20:17
> 
> I think that you have to join the Owlcat Discord server before you can access that link.

Yes. The problem is not that I couldn't access the link, the problem is that to join the Owlcat Discord you need to follow the link (in the README.md) and that no longer works.

**Comment by SkebbZ** [comment] 2022-09-01 06:56
https://discord.gg/xArYYVQ3

**Comment by RichardHeywood** [comment] 2022-09-01 13:37
For anybody having issues downloading the beta version of the recent patch from Discord, here is the direct zip file. I was able to install it and Toy Box began working for me. I haven't tested everything yet, but so far it appears fully functional. 

[0ToyBox0.zip](https://github.com/cabarius/ToyBox/files/9470281/0ToyBox0.zip)

**Closed** 2022-09-05 17:35 UTC
Labels: bug
