### ISSUE TITLE
Map broken in Controller Mode

### ISSUE THREAD

**Issue by SpykeAlpha** [cabarius/ToyBox#1057] opened 2023-11-28 00:28 UTC
### Description of the bug

While Toybox is running, and the game is in Controller Mode, the in-game map screen is broken. 

It draws the map, minus any icons. The controller is still controlling the player, and not the trapezoid shown on that map (which doesn't move from the original draw). 

To get rid of the map, you have to pull up the character's inventory (or other full screen). 

### Steps To Reproduce

Run Toybox
Make sure you are in Controller mode
Open map

### Expected Behavior

Should be able to see the map with all icons as well as the ability to move the trapezoid. 

### Toybox Version

1.5.8

### Operating System

Windows 11

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.2.1a

**Comment by CasDragon** [comment] 2023-11-28 01:17
Dupe of #999

**Closed by CasDragon** 2023-11-28 01:17 UTC
Labels: bug, broken gameplay
