### ISSUE TITLE
Feat multiplier tries to apply retroactively to companions

### ISSUE THREAD

**Issue by SoulInShadow** [cabarius/ToyBox#302] opened 2021-09-22 00:16 UTC
As the title says, when I level up my companions with the feat multiplier set higher than one, the game attempts to apply the multiplier to the levels the companion starts with. These additional feats/features do not appear on the character once level-up has concluded but it does effect the level up process itself, for example preventing options from being selected because the game thinks they have already been acquired (especially obvious when there is a selection from a small list of feats, like Lann when selecting bow specific feats). This can also result in being able to select options without meeting the prerequisites normally, like being able to select a wider selection of hexes for Camellia

**Comment by ArcaneTrixter** [comment] 2021-09-22 14:30
Which version of Toybox are you using?

**Comment by MatheusSLF** [comment] 2021-09-22 16:07
The last time I played using Toybox in 1.3.5 version, the same thing was happening to me when I set feat multiplier higher than one. Apparently from what I could verify, it is some problem related to the automatic selection of class recommended feats/abilities.

**Comment by ArcaneTrixter** [comment] 2021-09-22 16:27
The reason I was asking is that was (supposed to be, anyway) fixed in 1.3.5 for companions recruited after that point.

**Comment by ArcaneTrixter** [comment] 2021-09-23 03:11
I've started looking into it. I can confirm it's weird and retroactive.

**Comment by SoulInShadow** [comment] 2021-09-23 05:07
Sorry, I was at work, this was on 1.3.7

**Closed** 2021-09-25 18:11 UTC
Labels: bug
