### ISSUE TITLE
Gestalt Doesn't Work with Archetypes

### ISSUE THREAD

**Issue by Aruetii** [cabarius/ToyBox#145] opened 2021-09-09 23:57 UTC
Under Choose Default Multiclass I select any class, and then select the Archetype, such as Scaled Fist Monk or Crossblooded Sorcerer. This works as you would expect until you get to Name, once you enter anything or hit the randomized name button it erases the archetype and goes with the default class. Sometimes it only shows the base class at all in Class Progression.

https://gyazo.com/91046bacab4290f1e00306a0c2b3a130
https://gyazo.com/d6fad685d9edfb899c4a9a62f9bfa177

Really enjoying playing around with things though, looking forward to how the mod continues to grow.

**Comment by LadyAlekto** [comment] 2021-09-11 13:18
As per manual/guide for subclasses you must spend at least 1 level into it, then set as gestalt

**Comment by DreamTourist** [comment] 2021-09-11 18:21
> As per manual/guide for subclasses you must spend at least 1 level into it, then set as gestalt

The issue is about a bug with Multiple Classes in Character Creation. Currently the mod's Multiple Classes feature only works in Level Up.

**Comment by DreamTourist** [comment] 2021-09-13 02:35
Bug seems to be FIXED as of v1-3-0.

**Closed** 2021-09-14 04:55 UTC
