### ISSUE TITLE
Kineticist burn reduction on 1.3.12

### ISSUE THREAD

**Issue by fazliamri** [cabarius/ToyBox#346] opened 2021-09-26 14:00 UTC
**Describe the bug**
Im on 1.3.12 and i think the kineticist burn reduction slider is not working.

**To Reproduce**

**Expected behavior**

**Save Files**
To help us reproduce your issue, please attach a named *save file*
Please zip it or GitHub will not accept it.

**Screenshots**

**Settings**
Please attach your settings.xml file from the mod folder

**Version Info:**
 - ToyBox Version: [e.g. 1.3.4]

**Additional context**

**Comment by ArcaneTrixter** [comment] 2021-09-27 18:05
I am unable to reproduce this. Setting burn reduction to 0
![image](https://user-images.githubusercontent.com/6569164/134961476-90d606c3-c76a-4420-8c15-c7d7405c5868.png)
vs setting burn reduction to 2
![image](https://user-images.githubusercontent.com/6569164/134961544-2376de16-d716-4553-9bcc-37c763210596.png)

**Comment by ArcaneTrixter** [comment] 2021-09-30 17:22
Given no additional cases and a direct inability to reproduce by multiple users, I'm closing this. If you have an example that allows this to be reproduced, please re-open this issue.

**Closed by ArcaneTrixter** 2021-09-30 17:22 UTC
Labels: bug
