### ISSUE TITLE
<title>Increase carry capacity 82 and bigger makes me overencumbred

### ISSUE THREAD

**Issue by FanFanMi** [cabarius/ToyBox#1085] opened 2024-03-23 13:07 UTC
### Description of the bug

Setting the option "Increase carry capacity" to 82 and over makes me overencumbered in a new game with an empty inventory. Below works fine. I also equipment weights zero. 

https://prnt.sc/3eIabmFwh23g

Mods I use: Auto Mount, Bubble Tweaks, Mewsifer Console and Menu, Mod Menu, ToyBox and Wrath Patches. 

### Steps To Reproduce

CTRL F10, first tab, scroll to Other Multipliers, set Increase Carry Capacity to 100, enjoy. I did altered plenty of other options through the mod, if that may affect the outcome. 

### Expected Behavior

You get the red bag with overencumbered and can't move stuff.

### Log Files

[Player.log](https://github.com/cabarius/ToyBox/files/14731609/Player.log)
[GameLogFull.txt](https://github.com/cabarius/ToyBox/files/14731610/GameLogFull.txt)

### Save File

[Manual_1_Underground_Caves_of_Kenabres__16_Arodus__VIII__4715__12_28_05.zip](https://github.com/cabarius/ToyBox/files/14731614/Manual_1_Underground_Caves_of_Kenabres__16_Arodus__VIII__4715__12_28_05.zip)

### Screenshots

![Screenshot_2](https://github.com/cabarius/ToyBox/assets/13280831/67bd7da9-fa52-4503-a1ca-3d630e069577)

### Settings

[Settings.zip](https://github.com/cabarius/ToyBox/files/14731620/Settings.zip)

### Toybox Version

1.5.10a

### Operating System

Windows 10

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.2.4p

**Comment by CasDragon** [comment] 2024-03-24 22:26
I have the slider set to 100 by default, and I loaded up all my test saves, as well as the save you provided, and was not encumbered in any of the saves. I also don't see any glaring issues in your log files. Will tag @xADDBx because maybe he has an idea, but I'm unable to reproduce it on my end, sorry.

**Comment by FanFanMi** [comment] 2024-03-25 07:18
Thanks, it's not really a big issue, I just wanted to let you know. 70 is ok.

**Comment by FanFanMi** [comment] 2024-03-25 09:22
It probably is a conflict with a setting from Toy or another one of the mods, if it were a big issue I'd try to see if it's another mod or another Toy setting. But it's nothing.

**Comment by FanFanMi** [comment] 2024-03-28 21:09
Hm, I think it might be related to my 100+ edited stats. Too lazy to check, but I am 94.4394% sure that's the problem.

**Comment by CasDragon** [comment] 2024-05-29 23:10
Closing due to possibly not being an actual bug?

**Closed by CasDragon** 2024-05-29 23:10 UTC
Labels: bug, broken feature
