### ISSUE TITLE
Gestalt leveling after respec not allowing the selection of class features.

### ISSUE THREAD

**Issue by jonlost** [cabarius/ToyBox#1084] opened 2024-03-03 04:32 UTC
### Description of the bug

When leveling up with gestalt turn on after using the Respec Mod, I am not able to select specific class features that have multiple choices of the gestalt class.

However, when I change the main class that is being leveled up, it will then allow me to select the class feature of the gestalt class.

This is happening with Arueshalee at the moment, but I did experience the issue with Woljif earlier in my run.

### Steps To Reproduce

1. Use the latest version of the Respec Mod to respec a character to level 1.
2. Close the Mod Manager and go through the process of creating the level 1 character.
3. Level that character up to level 2, but choose the gestalt class.
4. Open ToyBox and go to the Party tab.
5. Check the second class to be the gestalt class and have "Multiple Classes On Level-Up" checked.
6. Level up the character until a choice for a class feature comes up for the gestalt class.

### Expected Behavior

All class features should be accessible when leveling a gestalt character.

### Save File

Using these mods with this save file.

Scaling Cantrips v1.5.8 (https://github.com/RealityMachina/Scaling-Cantrips)
Respec Mod v1.10.16 (https://github.com/BarleyFlour/RespecMod/releases)
VisualAdjustments 2 v1.2.6 (https://github.com/BarleyFlour/VisualAdjustments2/)
ToyBox v1.5.10a (https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/8?tab=posts&BH=0)

[Save.zip](https://github.com/cabarius/ToyBox/files/14471772/Save.zip)

### Screenshots

![ISSUE1](https://github.com/cabarius/ToyBox/assets/161994345/02a5b3cb-a94e-48ce-a1c9-97ab976018c1)
![ISSUE2](https://github.com/cabarius/ToyBox/assets/161994345/1927f8b0-a47b-462f-93e5-346a06ec318a)

### Toybox Version

1.5.10a

### Operating System

Windows

### What game are you using Toybox on?

Pathfinder Wrath of the Righteous

### Game Version

2.2.4p

**Comment by CasDragon** [comment] 2024-03-06 18:46
Dupe of #922 (Seriously, it is. The bug causing that causes this one)

**Closed by CasDragon** 2024-03-06 18:46 UTC
Labels: bug, gestalt-bugs
